dic_divisas  = {'1 (EUR/USD) Euro/USA Dollar': ['EUR/USD', 'EURUSD=X'],              '2 (USD/JPY) USA Dollar/JAP Yen': ['USD/JPY', 'USDJPY=X'],        '3 (GBP/USD) GBR Pound/USA Dollar': ['GBP/USD', 'GBPUSD=X'],  
                '4 (USD/TRY) USA Dollar/TUR Lire': ['USD/TRY', 'USDTRY=X'],          '5 (USD/CHF) USA Dollar/SWI Franc': ['USD/CHF', 'USDCHF=X'],      '6 (USD/CAD) USA Dollar/CAN Dollar': ['USD/CAD', 'USDCAD=X'], 
                '7 (EUR/JPY) Euro/JAP Yen': ['EUR/JPY', 'EURJPY=X'],                 '8 (AUD/USD) AUS Dollar/USA Dollar': ['AUD/USD', 'AUDUSD=X'],     '9 (NZD/USD) NZL Dollar/USA Dollar': ['NZD/USD', 'NZDUSD=X'], 
                '10 (EUR/GBP) Euro/GBR Pound': ['EUR/GBP', 'EURGBP=X'],              '11 (EUR/CHF) Euro/SWI Franc': ['EUR/CHF', 'EURCHF=X'],           '12 (AUD/JPY) AUS Dollar/JAP Yen': ['AUD/JPY', 'AUDJPY=X'], 
                '13 (GBP/JPY) GBR Pound/JAP Yen': ['GBP/JPY', 'GBPJPY=X'],           '14 (CHF/JPY) SWI Franc/JAP Yen': ['CHF/JPY', 'CHFJPY=X'],        '15 (EUR/CAD) Euro/CAN Dollar': ['EUR/CAD', 'EURCAD=X'],      
                '16 (AUD/CAD) AUS Dollar/CAN Dollar': ['AUD/CAD', 'AUDCAD=X'],       '17 (CAD/JPY) CAN Dollar/JAP Yen': ['CAD/JPY', 'CADJPY=X'],       '18 (NZD/JPY) NZL Dollar/JAP Yen': ['NZD/JPY', 'NZDJPY=X'], 
                '19 (AUD/NZD) AUS Dollar/NZL Dollar': ['AUD/NZD', 'AUDNZD=X'],       '20 (GBP/AUD) GBR Pound/AUS Dollar': ['GBP/AUD', 'GBPAUD=X'],     '21 (EUR/AUD) Euro/AUS Dollar': ['EUR/AUD', 'EURAUD=X'],      
                '22 (GBP/CHF) GBR Pound/SWI Franc': ['GBP/CHF', 'GBPCHF=X'],         '23 (EUR/NZD) Euro/NZL Dollar': ['EUR/NZD', 'EURNZD=X'],          '24 (AUD/CHF) AUS Dollar/SWI Franc': ['AUD/CHF', 'AUDCHF=X'], 
                '25 (GBP/NZD) GBR Pound/NZL Dollar': ['GBP/NZD', 'GBPNZD=X'],        '26 (USD/INR) USA Dollar/IND Rupee': ['USD/INR', 'USDINR=X'],     '27 (USD/CNY) USA Dollar/CHN Yuan': ['USD/CNY', 'USDCNY=X'], 
                '28 (USD/SGD) USA Dollar/SGP Dollar': ['USD/SGD', 'USDSGD=X'],       '29 (USD/HKD) USA Dollar/HKG Dollar': ['USD/HKD', 'USDHKD=X'],    '30 (USD/DKK) USA Dollar/DNK Krone': ['USD/DKK', 'USDDKK=X'], 
                '31 (GBP/CAD) GBR Pound/CAN Dollar': ['GBP/CAD', 'GBPCAD=X'],        '32 (USD/SEK) USA Dollar/SWE Krona': ['USD/SEK', 'USDSEK=X'],     '33 (USD/RUB) USA Dollar/RUS Ruble': ['USD/RUB', 'USDRUB=X'], 
                '34 (USD/ILS) USA Dollar/ILS': ['USD/ILS', 'USDILS=X'],              '35 (USD/MXN) USA Dollar/MEX Peso': ['USD/MXN', 'USDMXN=X'],      '36 (USD/ZAR) USA Dollar/ZAF Rand': ['USD/ZAR', 'USDZAR=X'],
                '37 (CAD/CHF) CAN Dollar/SWI Franc': ['CAD/CHF', 'CADCHF=X'],        '38 (NZD/CAD) NZL Dollar/CAN Dollar': ['NZD/CAD', 'NZDCAD=X'],    '39 (NZD/CHF) NZL Dollar/SWI Franc': ['NZD/CHF', 'NZDCHF=X']}

dic_criptos  = {'1 (BTC-USD) Bitcoin': ['BTC-USD', 'BTC-USD'],                       '2 (ETH-USD) Ethereum': ['ETH-USD', 'ETH-USD'],                   '3 (BNB-USD) BNB': ['BNB-USD', 'BNB-USD'], 
                '4 (USDC-USD) USD Coin': ['USDC-USD', 'USDC-USD'],                   '5 (XRP-USD) XRP': ['XRP-USD', 'XRP-USD'],                        '6 (HEX-USD) HEX': ['HEX-USD', 'HEX-USD'], 
                '7 (ADA-USD) Cardano': ['ADA-USD', 'ADA-USD'],                       '8 (MATIC-USD) Polygon': ['MATIC-USD', 'MATIC-USD'],              '9 (STETH-USD) Lido Staked ETH': ['STETH-USD', 'STETH-USD'], 
                '10 (DOGE-USD) Dogecoin': ['DOGE-USD', 'DOGE-USD'],                  '11 (SOL-USD) Solana': ['SOL-USD', 'SOL-USD'],                    '12 (DOT-USD) Polkadot': ['DOT-USD', 'DOT-USD'], 
                '13 (WTRX-USD) Wrapped TRON': ['WTRX-USD', 'WTRX-USD'],              '14 (DAI-USD) Dai': ['DAI-USD', 'DAI-USD'],                       '15 (TRX-USD) TRON': ['TRX-USD', 'TRX-USD'], 
                '16 (SHIB-USD) Shiba Inu': ['SHIB-USD', 'SHIB-USD'],                 '17 (LTC-USD) Litecoin': ['LTC-USD', 'LTC-USD'],                  '18 (AVAX-USD) Avalanche': ['AVAX-USD', 'AVAX-USD'], 
                '19 (UNI7083-USD) Uniswap': ['UNI7083-USD', 'UNI7083-USD'],          '20 (WBTC-USD) Wrapped Bitcoin': ['WBTC-USD', 'WBTC-USD'],        '21 (ATOM-USD) Cosmos': ['ATOM-USD', 'ATOM-USD'], 
                '22 (LINK-USD) Chainlink': ['LINK-USD', 'LINK-USD'],                 '23 (LEO-USD) UNUS SED LEO': ['LEO-USD', 'LEO-USD'],              '24 (TMG-USD) T-mac DAO': ['TMG-USD', 'TMG-USD'], 
                '25 (TON11419-USD) Toncoin': ['TON11419-USD', 'TON11419-USD'],       '26 (OKB-USD) OKB': ['OKB-USD', 'OKB-USD'],                       '27 (ETC-USD) Ethereum Classic': ['ETC-USD', 'ETC-USD'], 
                '28 (XMR-USD) Monero': ['XMR-USD', 'XMR-USD'],                       '29 (FIL-USD) Filecoin': ['FIL-USD', 'FIL-USD'],                  '30 (BCH-USD) Bitcoin Cash': ['BCH-USD', 'BCH-USD'], 
                '31 (XLM-USD) Stellar': ['XLM-USD', 'XLM-USD'],                      '32 (APT21794-USD) Aptos': ['APT21794-USD', 'APT21794-USD'],      '33 (LDO-USD) Lido DAO': ['LDO-USD', 'LDO-USD'], 
                '34 (TUSD-USD) TrueUSD': ['TUSD-USD', 'TUSD-USD'],                   '35 (CRO-USD) Cronos': ['CRO-USD', 'CRO-USD'],                    '36 (HBAR-USD) Hedera': ['HBAR-USD', 'HBAR-USD'], 
                '37 (NEAR-USD) NEAR Protocol': ['NEAR-USD', 'NEAR-USD'],             '38 (VET-USD) VeChain': ['VET-USD', 'VET-USD'],                   '39 (ICP-USD) Internet Computer': ['ICP-USD', 'ICP-USD'], 
                '40 (APE18876-USD) ApeCoin': ['APE18876-USD', 'APE18876-USD'],       '41 (ALGO-USD) Algorand': ['ALGO-USD', 'ALGO-USD'],               '42 (QNT-USD) Quant': ['QNT-USD', 'QNT-USD'], 
                '43 (BTCB-USD) Bitcoin BEP2': ['BTCB-USD', 'BTCB-USD'],              '44 (GRT6719-USD) The Graph': ['GRT6719-USD', 'GRT6719-USD'],     '45 (STX4847-USD) Stacks': ['STX4847-USD', 'STX4847-USD'],
                '46 (FTM-USD) Fantom': ['FTM-USD', 'FTM-USD'],                       '47 (EOS-USD) EOS': ['EOS-USD', 'EOS-USD'],                       '48 (WBNB-USD) Wrapped BNB': ['WBNB-USD', 'WBNB-USD'], 
                '49 (XTZ-USD) Tezos': ['XTZ-USD', 'XTZ-USD'],                        '50 (BIT11221-USD) BitDAO': ['BIT11221-USD', 'BIT11221-USD'],     '51 (MANA-USD) Decentraland': ['MANA-USD', 'MANA-USD'], 
                '52 (AAVE-USD) Aave': ['AAVE-USD', 'AAVE-USD'],                      '53 (EGLD-USD) MultiversX': ['EGLD-USD', 'EGLD-USD'],             '54 (FLOW-USD) Flow': ['FLOW-USD', 'FLOW-USD'], 
                '55 (FRAX-USD) Frax': ['FRAX-USD', 'FRAX-USD'],                      '56 (IMX10603-USD) ImmutableX': ['IMX10603-USD', 'IMX10603-USD'], '57 (HBTC-USD) Huobi BTC': ['HBTC-USD', 'HBTC-USD'], 
                '58 (AXS-USD) Axie Infinity': ['AXS-USD', 'AXS-USD'],                '59 (SAND-USD) The Sandbox': ['SAND-USD', 'SAND-USD'],            '60 (KCS-USD) KuCoin Token': ['KCS-USD', 'KCS-USD'], 
                '61 (USDP-USD) Pax Dollar': ['USDP-USD', 'USDP-USD'],                '62 (CFX-USD) Conflux': ['CFX-USD', 'CFX-USD'],                   '63 (OP-USD) Optimism': ['OP-USD', 'OP-USD'], 
                '64 (CHZ-USD) Chiliz': ['CHZ-USD', 'CHZ-USD'],                       '65 (NEO-USD) Neo': ['NEO-USD', 'NEO-USD'],                       '66 (MKR-USD) Maker': ['MKR-USD', 'MKR-USD'], 
                '67 (RPL-USD) Rocket Pool': ['RPL-USD', 'RPL-USD'],                  '68 (LUNC-USD) Terra Classic': ['LUNC-USD', 'LUNC-USD'],          '69 (KLAY-USD) Klaytn': ['KLAY-USD', 'KLAY-USD'], 
                '70 (SNX-USD) Synthetix': ['SNX-USD', 'SNX-USD'],                    '71 (MINA-USD) Mina': ['MINA-USD', 'MINA-USD'],                   '72 (CRV-USD) Curve DAO Token': ['CRV-USD', 'CRV-USD'], 
                '73 (BSV-USD) Bitcoin SV': ['BSV-USD', 'BSV-USD'],                   '74 (CAKE-USD) PancakeSwap': ['CAKE-USD', 'CAKE-USD'],            '75 (BTTOLD-USD) BitTorrent': ['BTTOLD-USD', 'BTTOLD-USD'], 
                '76 (HT-USD) Huobi Token': ['HT-USD', 'HT-USD'],                     '77 (TNC5524-USD) TNC Coin': ['TNC5524-USD', 'TNC5524-USD'],      '78 (FXS-USD) Frax Share': ['FXS-USD', 'FXS-USD'],
                '79 (BTT-USD) BitTorrent-New': ['BTT-USD', 'BTT-USD'],               '80 (DASH-USD) Dash': ['DASH-USD', 'DASH-USD'],                   '81 (GMX11857-USD) GMX': ['GMX11857-USD', 'GMX11857-USD'],
                '82 (GUSD-USD) Gemini Dollar': ['GUSD-USD', 'GUSD-USD'],             '83 (XEC-USD) eCash': ['XEC-USD', 'XEC-USD'],                     '84 (GT-USD) GateToken': ['GT-USD', 'GT-USD'], 
                '85 (MIOTA-USD) IOTA': ['MIOTA-USD', 'MIOTA-USD'],                   '86 (ZEC-USD) Zcash': ['ZEC-USD', 'ZEC-USD'],                     '87 (AGIX-USD) SingularityNET': ['AGIX-USD', 'AGIX-USD'], 
                '88 (PAXG-USD) PAX Gold': ['PAXG-USD', 'PAXG-USD'],                  '89 (BGB-USD) Bitget Token': ['BGB-USD', 'BGB-USD'],              '90 (TWT-USD) Trust Wallet Token': ['TWT-USD', 'TWT-USD'], 
                '91 (KAVA-USD) Kava': ['KAVA-USD', 'KAVA-USD'],                      '92 (XAUT-USD) Tether Gold': ['XAUT-USD', 'XAUT-USD'],            '93 (RNDR-USD) Render Token': ['RNDR-USD', 'RNDR-USD'], 
                '94 (RUNE-USD) THORChain': ['RUNE-USD', 'RUNE-USD'],                 '95 (ZIL-USD) Zilliqa': ['ZIL-USD', 'ZIL-USD'],                   '96 (XDC-USD) XDC Network': ['XDC-USD', 'XDC-USD'], 
                '97 (LRC-USD) Loopring': ['LRC-USD', 'LRC-USD'],                     '98 (CVX-USD) Convex Finance': ['CVX-USD', 'CVX-USD'],            '99 (1INCH-USD) 1inch Network': ['1INCH-USD', '1INCH-USD'], 
                '100 (WEMIX-USD) WEMIX': ['WEMIX-USD', 'WEMIX-USD'],                 '101 (OSMO-USD) Osmosis': ['OSMO-USD', 'OSMO-USD'],               '102 (ENJ-USD) Enjin Coin': ['ENJ-USD', 'ENJ-USD'], 
                '103 (FEI-USD) Fei': ['FEI-USD', 'FEI-USD'],                         '104 (CSPR-USD) Casper': ['CSPR-USD', 'CSPR-USD'],                '105 (DYDX-USD) dYdX': ['DYDX-USD', 'DYDX-USD'], 
                '106 (FLR-USD) Flare': ['FLR-USD', 'FLR-USD'],                       '107 (SSV-USD) ssv.network': ['SSV-USD', 'SSV-USD'],              '108 (XRD-USD) Radix': ['XRD-USD', 'XRD-USD'], 
                '109 (FTT-USD) FTX Token': ['FTT-USD', 'FTT-USD'],                   '110 (ETHW-USD) EthereumPoW': ['ETHW-USD', 'ETHW-USD'],           '111 (T-USD) Threshold': ['T-USD', 'T-USD'], 
                '112 (BAT-USD) Basic Attention Token': ['BAT-USD', 'BAT-USD'],       '113 (ROSE-USD) Oasis Network': ['ROSE-USD', 'ROSE-USD'],         '114 (NEXO-USD) Nexo': ['NEXO-USD', 'NEXO-USD'], 
                '115 (WOO-USD) WOO Network': ['WOO-USD', 'WOO-USD'],                 '116 (XEM-USD) NEM': ['XEM-USD', 'XEM-USD'],                      '117 (FET-USD) Fetch.ai': ['FET-USD', 'FET-USD'], 
                '118 (MAGIC14783-USD) MAGIC': ['MAGIC14783-USD', 'MAGIC14783-USD'],  '119 (NXM-USD) NXM': ['NXM-USD', 'NXM-USD'],                      '120 (BONE11865-USD) Bone ShibaSwap': ['BONE11865-USD', 'BONE11865-USD'],
                '121 (TFUEL-USD) Theta Fuel': ['TFUEL-USD', 'TFUEL-USD'],            '122 (ANKR-USD) Ankr': ['ANKR-USD', 'ANKR-USD'],                  '123 (FLOKI-USD) FLOKI': ['FLOKI-USD', 'FLOKI-USD'],
                '124 (RVN-USD) Ravencoin': ['RVN-USD', 'RVN-USD'],                   '125 (COMP5692-USD) Compound': ['COMP5692-USD', 'COMP5692-USD'],  '126 (LUNA20314-USD) Terra': ['LUNA20314-USD', 'LUNA20314-USD'], 
                '127 (YFI-USD) yearn.finance': ['YFI-USD', 'YFI-USD'],               '128 (BAL-USD) Balancer': ['BAL-USD', 'BAL-USD'],                 '129 (HOT2682-USD) Holo': ['HOT2682-USD', 'HOT2682-USD'], 
                '130 (CELO-USD) Celo': ['CELO-USD', 'CELO-USD'],                     '131 (MOB-USD) MobileCoin': ['MOB-USD', 'MOB-USD'],               '132 (USDJ-USD) USDJ': ['USDJ-USD', 'USDJ-USD'], 
                '133 (MASK8536-USD) Mask Network': ['MASK8536-USD', 'MASK8536-USD'], '134 (QTUM-USD) Qtum': ['QTUM-USD', 'QTUM-USD'],                  '135 (KSM-USD) Kusama': ['KSM-USD', 'KSM-USD'], 
                '136 (INJ-USD) Injective': ['INJ-USD', 'INJ-USD'],                   '137 (HNT-USD) Helium': ['HNT-USD', 'HNT-USD'],                   '138 (DCR-USD) Decred': ['DCR-USD', 'DCR-USD'], 
                '139 (GALA-USD) Gala': ['GALA-USD', 'GALA-USD'],                     '140 (DFI-USD) DeFiChain': ['DFI-USD', 'DFI-USD'],                '141 (GNO-USD) Gnosis': ['GNO-USD', 'GNO-USD'], 
                '142 (ASTR-USD) Astar': ['ASTR-USD', 'ASTR-USD'],                    '143 (AR-USD) Arweave': ['AR-USD', 'AR-USD'],                     '144 (LN-USD) LINK': ['LN-USD', 'LN-USD'], 
                '145 (ENS-USD) Ethereum Name Service': ['ENS-USD', 'ENS-USD'],       '146 (ONE3945-USD) Harmony': ['ONE3945-USD', 'ONE3945-USD'],      '147 (BTG-USD) Bitcoin Gold': ['BTG-USD', 'BTG-USD'],
                '148 (SUSHI-USD) SushiSwap': ['SUSHI-USD', 'SUSHI-USD'],             '149 (AUDIO-USD) Audius': ['AUDIO-USD', 'AUDIO-USD'],             '150 (XCH-USD) Chia': ['XCH-USD', 'XCH-USD']}


dic_indices  = {'1 (ES35) IBEX 35': ['ES35', '^IBEX'],                               '2 (DJI) Dow Jones Industrial Average': ['DJI', '^DJI'],          '3 (US500) S&P 500': ['US500', '^GSPC'], 
                '4 (IXIC) NASDAQ Composite': ['IXIC', '^IXIC'],                      '5 (US2000) Russell 2000': ['US2000', '^RUT'],                    '6 (VIX) CBOE Volatility Index': ['VIX', '^VIX'], 
                '7 (GSPTSE) S&P/TSX Composite': ['GSPTSE', '^GSPTSE'],               '8 (BVSP) Bovespa': ['BVSP', '^BVSP'],                            '9 (MERV) S&P Merval': ['MERV', '^MERV'], 
                '10 (SPIPSA) S&P CLX IPSA': ['SPIPSA', '^IPSA'],                     '11 (MXX) S&P/BMV IPC': ['MXX', '^MXX'],                          '12 (DE40) DAX': ['DE40', '^GDAXI'],
                '13 (UK100) FTSE 100': ['UK100', '^FTSE'],                           '14 (FCHI) CAC 40': ['FCHI', '^FCHI'],                            '15 (STOXX50) Euro Stoxx 50': ['STOXX50', '^STOXX50E'], 
                '16 (AEX) AEX': ['AEX', '^AEX'],                                     '17 (IT40) FTSE MIB': ['IT40', 'FTSEMIB.MI'],                     '18 (PSI20) PSI': ['PSI20', 'PSI20.LS'], 
                '19 (BFX) BEL 20': ['BFX', '^BFX'],                                  '20 (ATX) ATX': ['ATX', '^ATX'],                                  '21 (OMXS30) OMX Stockholm 30': ['OMXS30', '^OMX'], 
                '22 (IMOEX) MOEX Russia': ['IMOEX', 'IMOEX.ME'],                     '23 (XU100) BIST 100': ['XU100', 'XU100.IS'],                     '24 (TA35) TA 35': ['TA35', 'TA35.TA'], 
                '25 (TASI) Tadawul All Share': ['TASI', '^TASI.SR'],                 '26 (JP225) Nikkei 225': ['JP225', '^N225'],                      '27 (AXJO) S&P/ASX 200': ['AXJO', '^AXJO'], 
                '28 (SSEC) Shanghai Composite': ['SSEC', '000001.SS'],               '29 (SZI) SZSE Component': ['SZI', '399001.SZ'],                  '30 (HK50) Hang Seng': ['HK50', '^HSI'],
                '31 (TWII) Taiwan Weighted': ['TWII', '^TWII'],                      '32 (KS11) KOSPI': ['KS11', '^KS11'],                             '33 (JKSE) Jakarta Stock Exchange Composite': ['JKSE', '^JKSE'], 
                '34 (NSEI) Nifty 50': ['NSEI', '^NSEI'],                             '35 (BSESN) BSE Sensex 30': ['BSESN', '^BSESN']}


dic_materias = {'1 (GC) Gold': ['GC', 'GC=F'],                                       '2 (SI) Silver': ['SI', 'SI=F'],                                  '3 (HG) Copper': ['HG', 'HG=F'], 
                '4 (PL) Platinum': ['PL', 'PL=F'],                                   '5 (PA) Palladium': ['PA', 'PA=F'],                               '6 (CL) Crude Oil': ['CL', 'CL=F'], 
                '7 (BF) Brent Crude Oil': ['LCO', 'BZ=F'],                           '8 (NG) Natural Gas': ['NG', 'NG=F'],                             '9 (RB) RBOB Gasoline': ['GPR', 'RB=F'], 
                '10 (ALI) Aluminum Futures': ['MAL', 'ALI=F'],                       '11 (MCU) Copper': ['MCU', 'HG=F'],                               '12 (ZW) USA Wheat': ['ZW', 'ZW=F'], 
                '13 (ZE) Rough Rice': ['RR', 'ZR=F'],                                '14 (ZC) Corn': ['ZC', 'ZC=F'],                                   '15 (ZS) Soybean': ['ZS', 'ZS=F'], 
                '16 (ZL) Soybean Oil': ['ZL', 'ZL=F'],                               '17 (ZM) Soybean Meal USA': ['ZM', 'ZM=F'],                       '18 (CT) Cotton': ['CT', 'CT=F'], 
                '19 (CC) Cocoa USA': ['CC', 'CC=F'],                                 '20 (KC) Coffee USA': ['KC', 'KC=F'],                             '21 (SB) Sugar USA': ['SB', 'SB=F'], 
                '22 (OJ) Orange Juice': ['OJ', 'OJ=F'],                              '23 (HE) Lean Hogs': ['LHc1', 'HE=F'],                            '24 (GF) Feeder Cattle': ['FC', 'GF=F'], 
                '25 (LBS) Lumber': ['LBc1', 'LBSK23.CME'],                           '26 (ZO) Oat': ['O', 'ZO=F']}